# Generated by Django 4.1 on 2022-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsapp', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
    ]
