# Generated by Django 4.1 on 2022-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsapp', '0003_patient_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
