# Generated by Django 3.2.5 on 2022-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsapp', '0004_alter_patient_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
